### ISSUE TITLE
Decrementing values is not possible

### ISSUE THREAD

**Issue by J00LZZ** [NULLx76/counter#2]
It would be cool if the values could be decremented, maybe using patch?

**Comment by NULLx76** [comment]
Increment should probably also go over patch rather than PUT, I propose the following for PATCH:

**To Increment**
```json
{ "op": "increment"}
```

**To Decrement**
```json
{ "op": "decrement"}
```

This would then deprecate incrementing through PUT

**Comment by J00LZZ** [comment]
Oh that would work nicely, I'll try to implement that and send a PR!
